topics:
  - topic: "/teamgrit/image/raw"
    name: "front_camera"
    host: "your_host"
    port: "your_port"
    endpoint: "your_endpoint"
    type: "VIDEO"
  - topic: "/teamgrit/sensor"
    name: "sensor"
    host: "your_host"
    port: "your_port"
    endpoint: "your_endpoint"
    type: "SENSOR"
  - topic: "/teamgrit/lidar"
    name: "lidar"
    host: "your_host"
    port: "your_port"
    endpoint: "your_endpoint"
    type: "LIDAR"
